### ISSUE TITLE
Using a Windows laptop

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7950/Discussion#28]
From @stonedas:

> I have a Lenovo PC and I know that you recommended a Mac or Linux but there is no way I could have access to one of those for this class so I am going to try to use my Lenovo. Could you let me know what I need to install to make my computer work for the course. Also, I started the crash course but I wasn't sure if I should follow the instructions for Mac/Linux or Windows. I appreciate your help.

You will not be able to use several important command line utilities in Windows. You have several options:

1. If you are using Windows 10 then you can try to use ["Developer Mode" to get access to a shell](http://molb7621.github.io/workshop/Classes/class-01.html#pc-laptops). I have never done this and don't know how far you will get with it. Based on [this post](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/), I'm not sure how well this is going to work (it's still beta?).

2. Another solution is to install VirtualBox and then Ubuntu Linux. If you get stuck we will help you get setup in the first class.

3. The easiest option is to use some builtin Windoze terminal and use our compute cluster tesla. Working on a cluster remotely takes some time to get used to, but saves the headache of setting up your own computer correctly.

**Comment by chrismit258** [comment]
I have Virtual Box installed on my PC and have used Ubuntu within Virtual Box for a previous class. However now when I open Virtual Box, it gives me a warning that I don't have very much space left (44 MB). I cannot figure out how to allocate more memory to the Virtual Box. Is this worth trying to fix, or should I just use Putty?
