### ISSUE TITLE
class recordings on canvas

### ISSUE THREAD

**Issue by kriemo** [MOLB7950/Discussion#29]
FYI. The class recordings are posted on Canvas. https://ucdenver.instructure.com/

Click on Panopto Lectures after you've accessed the MOLB7621 course.

**Comment by jayhesselberth** [comment]
Here is the direct link to Class 1 for those of you that don't have Canvas logins:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ca62cdd5-2e58-46d6-9470-359760bd0896

**Comment by jayhesselberth** [comment]
Class 2:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=addebe6d-c871-4f3d-9520-dfcb40d93033

**Comment by jayhesselberth** [comment]
Class 3:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=df748b0c-2e62-415d-8004-aefd892138e3

**Comment by jayhesselberth** [comment]
There was an issue with the class 4 upload (problem with Panopto on their end). I hope to fix this tomorrow morning.

**Comment by jayhesselberth** [comment]
Class 4, unfortunately there's a problem with the audio again, will get a more robust microphone for next class:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d64ea333-4bfd-43fd-9951-5387d34c2d4a

**Comment by jayhesselberth** [comment]
Class 5:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=50ed7842-cc40-4004-9027-6e7644a85ba9

**Comment by kriemo** [comment]
Class 6:
https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=50284fce-cf4a-4459-9e46-ade004865082

**Comment by jayhesselberth** [comment]
Class 7:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8813dcfc-7a6b-47f4-a95f-ad8b66a3af5d

**Comment by jayhesselberth** [comment]
Class 8:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=911d3790-2c64-4312-a132-15c7f0cc1c7c

**Comment by jayhesselberth** [comment]
Class 9:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b368ae16-c604-4efa-984c-9732db5b7cac

**Comment by kriemo** [comment]
Class 10:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=03c38a27-bf85-4975-bf7b-f3189ad96ad8

Also note that I added code to the MOLB7621/class-10/ RMarkdown to show how to make the two additional plots

**Comment by jayhesselberth** [comment]
I had an issue uploading Class 11. Hopefully will be fixed tomorrow.

**Comment by jayhesselberth** [comment]
Class 11:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=e56a6b06-e37a-4951-828f-7c591b374b67

**Comment by jayhesselberth** [comment]
Class 12:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d366739c-fe78-4153-a4c1-d549b9a45c22

**Comment by kriemo** [comment]
FYI, the panopto upload for the last class is having some issues that I'm working to resolve.

**Comment by jayhesselberth** [comment]
Class 14:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fc12db56-dc5b-452b-a75c-b979826b828c

**Comment by jayhesselberth** [comment]
Class 15:

(link should work after re-processing by David Paul)

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=66067db3-57a5-4af8-a370-cd96ac41586d

**Comment by kriemo** [comment]
Class 16:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a609842b-d70e-4311-a936-ec8f0e9aa7a0

**Comment by jayhesselberth** [comment]
Class 17:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=24f4528c-07ff-4fce-b3e9-9d119e3c3af9

**Comment by kriemo** [comment]
Class 18:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7695e22b-a3e1-4108-b70c-77d1b2949de0

**Comment by kriemo** [comment]
Class 20:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=52deff95-261e-49a0-9205-a2c4aa39cdcb

**Comment by kriemo** [comment]
Optional Class:

https://ucdenver.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=eb025c90-a202-4178-b65e-85fb55d1c1fc
