### ISSUE TITLE
Problem set 1 workflow in detail 

### ISSUE THREAD

**Issue by mandylr** [MOLB7950/Discussion#31]
Most of this we went over in class, but here's a reference for everyone. 

1. To start, [**fork** the repository](https://guides.github.com/activities/forking/). 
2. [Clone](http://gitref.org/creating/#clone) the repository to your computer. (Everyone should have done this already by today.)
3. **Modify the files.**
	* In terminal, navigate to the problem-set-1 folder
	* Using, [vim](http://www.openvim.com/), edit the answers.sh file.
		* Note, in problem-set-1, the answers.sh file has an example answer_1 workflow. You have to change this in several ways to get your program to work: 
			1. The datasets variable is set to a path on Jay's computer, you have to change this to reflect where your data-sets directory lives on your machine. (e.g. ``` $HOME/data-sets```) (What does the ```$HOME``` reference?)
			2. The states variable also needs to be changed. Where exactly does your ```states.tab.gz``` file live?
			3. The example question in answers.sh on github is "Which state has the highest population?", in the problem set, the real first question is "Which state has the lowest murder rate?". Edit the code for answer_1 so that you find the state with the lowest murder rate. 
			4. The last part of Jay's example uses a ```sed``` command,  the purpose of this is to remove the quotations around the state name. If future questions ask about state names copy ```sed 's/"//g'``` as the last command in the pipe to remove the quotation marks around the state name. 
			5. Try to understand how Jay assigned answer_1 as a variable and then referenced answer_1 variable in the ```echo "answer-1: $answer_1"``` command. (Why did he use double quotes (") instead of single quotes (') in this line?)
			6. Why does the line with the question on it (line 4) start with a #? 
			7. All the data files referenced in problem set 1 are located in the data-sets directory, in their respective folders. E.g., the sample.fa file is in the ```fasta/``` folder.
			8. For the remaining questions, create a variable ```answer_x=$(PUT CODE HERE)```, then reference the answer using ```echo "answer-x: $answer_x"``` Where x is the question number.
			9. Save your changes by typing ```:w``` or save and quit by typing ```:wq```
	* To test if your script works, run ```bash answers.sh```. It should spit out lines of text that say ```answer-1: California```, etc.
4. Once all the questions are completed, [commit](http://gitref.org/basic/#commit) changes you've made to the repository. 
From the terminal, in the problem-set-1 directory type:
```
git commit -m "PUT COMMENT HERE" answers.sh
```
This commits changes made only the answers.sh file.
5. [Push](http://gitref.org/remotes/#push) the changes up to Github. 
From the terminal, in the problem-set-1 directory type:
```
git push
```
6. Check answers on Travis CI
	* Stay tuned for more info on how to do this exactly. It's not necessary, it just lets you know if your answers are correct. 
	* If you really want to try it out, check out [Kent's post](https://github.com/MOLB7621/problem-set-1/issues/5).
7. Turn in the assignment by creating a [pull request](https://help.github.com/articles/creating-a-pull-request/). 

Most of this info can be found on the problem-set-1 github repository, but I thought some more explanation could help! If you're still struggling, take advantage of the [issues](https://github.com/MOLB7621/problem-set-1/issues) tab in problem-set-1 and this discussion board.

@MOLB7621/students

**Comment by chrismit258** [comment]
Hi, I completed the homework and entered the "git commit" command, which all seemed to work fine. However when I entered the "git push" command, I got this error message: 

error: The requested URL returned error: 403 Forbidden while accessing https://github.com/chrismit258/problem-set-1.git/info/refs
fatal: HTTP request failed

Any idea what went wrong? I am using tesla from a PC and I am in the problem-set-1 directory when I type this command. 

Thanks,
Christy

**Comment by kriemo** [comment]
There is an issue with git on tesla right now for some users. I believe the problem is that the old installed version of git does not support `https` access to your repository, so you need to use `SSH` instead. 

Can you try the following steps to add SSH access to your account? 

1) [Generate](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) a SSH key (use the default file location ~/.ssh/id_rsa)
2) [Add](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) the key to your github account
3) [Test](https://help.github.com/articles/testing-your-ssh-connection/)  your SSH connection

Then change your repository config settings to use `SSH` and try to push
```bash
cd problem-set-1/
git remote set-url origin git@github.com:chrismit258/problem-set-1.git
git push
```
If this doesn't work then we will find another solution. 
Thanks!

**Comment by mandylr** [comment]
I forgot an important part of doing the problem set!

After you've got your answers.sh script working and you think you're about ready to submit it, you need to run the run.sh script. 

```bash run.sh```

This will write all your answers to the answers.yml file. Alternatively, you can just redirect the output of answers.sh to answers.yml. 

```bash answers.sh > "answers.yml"```

Then when you go to submit your problem set, you need to commit and push both the answers.sh file **and** the answers.yml file. 

```
git commit -m "PUT MESSAGE HERE" answers.sh answers.yml
git push
```

NOW, you'll have a completed problem set. Sorry for any confusion above. 

@MOLB7621/students

**Comment by chrismit258** [comment]
@kriemo , I tried to add SSH access to my account. I was able to generate a SSH key. I am having trouble adding it to my github account. My terminal doesn't recognize the "clip" command. Suggestions? 

Thanks,
Christy

**Comment by jayhesselberth** [comment]
It should be a simple copy / paste from the terminal to the relevant section in your github account settings; you don't need `clip` per se (just highlight with your mouse, copy, then paste in the website)

**Comment by chrismit258** [comment]
@jayhesselberth , I copied and pasted ~/.ssh/id_rsa.pub from the terminal into my github page (and tried it without the ~, /, and .) and each time I get this message: 

Key is invalid. It must begin with 'ssh-ed25519', 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'. Check that you're copying the public half of the key

**Comment by kriemo** [comment]
@chrismit258 
Copy the contents of the `~/.ssh/id_rsa.pub` file
```bash
$ cat ~/.ssh/id_rsa.pub
#copy the output here, but not the command
```

**Comment by jayhesselberth** [comment]
you need to copy the key itself, not the filename for the key. Here's mine:

```bash
$ cat ~/.ssh/id_rsa.pub

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQDsoKrjcMhnloQ+16bRvyuKC2te833r5HLKafqYrtFENpHngvrG/y6q1LIKcDJQ5Q+79ZASGDnfiTLvk8GyVB8GuqZsJj8TW0GtEqEBk1myA0u4FHOwYBqCQNEj+ZzNf9X3rtSukOdLAB8RI6iiikDBX5lDDDZu5BGrbBewHbgOKhXyAYxMScQD05/dh80WUKWBaziyWV6UKBOF/JyeFwH0L1eTcFpX30h7xjSIoHlyLp6cRVUyK7/G1qMdG3JWzzV1ybNQG/k4W5xybjibHinumNBkig/WnNwRPUSq+2xiKTbwLxZO6M5Yp1J5TIQwnYPoNuyJ5H0+RByoz5AZr9 jayhesselberth@Jays-MacBook-Pro.local
```

You need to copy all of the key (starting with the ssh-rsa bit and ending with your username@host) into your github account keys.

**Comment by chrismit258** [comment]
@kriemo @jayhesselberth  I think it worked. Thanks for the help. Will I have to do this every time I submit homework, or will it just use SSH from now on when I type "git push"?

**Comment by jayhesselberth** [comment]
Should be just this time you need to add your key. Just make sure you use SSH when you clone.
