### ISSUE TITLE
RStudio installation for Tuesday

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7950/Discussion#38]
Please install [RStudio](https://www.rstudio.com/products/rstudio/download/) on your laptops before Tuesday.

If you have a Mac, you can install rstudio and R with homebrew.:

```bash
brew install homebrew/science/r-3.3.2
brew install Caskroom/cask/rstudio
```

Once RStudio is installed, install the [tidyverse](http://tidyverse.org/) and [valr](http://rnabioco.github.io/valr/):

```r
install.packages(c('tidyverse', 'valr'))
```

@MOLB7621/students

**Comment by bentleyd** [comment]
Thanks Mandy, Will do, d.
On Feb 18, 2017, at 1:07 PM, Jay Hesselberth <notifications@github.com<mailto:notifications@github.com>> wrote:


Please install RStudio<https://www.rstudio.com/products/rstudio/download/> on your laptops before Tuesday.

If you have a Mac, you can install rstudio and R with homebrew.:

brew install homebrew/science/r-3.3.2
brew install Caskroom/cask/rstudio

Once RStudio is installed, install the tidyverse<http://tidyverse.org/> and valr<http://rnabioco.github.io/valr/>:

install.packages(c('tidyverse', 'valr'))

@MOLB7621/students<https://github.com/orgs/MOLB7621/teams/students>

**Comment by tshaikh10** [comment]
Hi Jay,

I had previously installed RStudio and R on my Mac after you and I had
spoken a few weeks ago. They are in my Applications folder. Should I still
download them within the Terminal as directed above?

Also, I have a tesla account. Will I need my login info for class tomorrow?

Thanks,
Tamim

**Comment by jayhesselberth** [comment]
If you already have R and RStudio installed, no need to reinstall. It's just easier to stay up to date with homebrew.

We won't be using tesla at all tomorrow.

**Comment by bentleyd** [comment]
Hi Jay, Not sure what this is about.
cheers, David,
________________________________
