### ISSUE TITLE
Additional R-esouces: Swirl & Tidy data paper

### ISSUE THREAD

**Issue by lkwhite** [MOLB7950/Discussion#42]
A couple more optional but useful resources that go into more depth on topics from class today:

- [Tidyr vignette](cran.r-project.org/pub/R/web/packages/tidyr/vignettes/tidy-data.html): this is a short rundown on the Tidyr package and the rationale for tidying data written by Hadley Wickham, the creator of the tidyverse (that is, the R packages tidyr, dplyr, etc). The vignette is written in R markdown, and links to a longer paper on the same subject.
- [Swirlstats](http://swirlstats.com/) is the homepage for the **Swirl** package, a tutorial for R and various packages that works _inside Rstudio itself_. You can read about it on that site, or you can just type the following in your R console to get started:
```
install.packages('swirl')
library(swirl)
```
Once you load the library, Swirl will begin prompting you with commands right in the terminal. It will ask you to clean up your workspace (save anything you need first, like notes from class!) and then tell you to type ```swirl()``` to begin. It will also ask you for your name - be sure to give it the same exact name each time if you want it to keep track of and save your progress. FYI, you can type ```bye()``` at any point to close Swirl.

If you feel like you need a _very basic_ introduction to R, go ahead and load the **R programming** course. Otherwise, you can do  ```install_course("Getting_and_Cleaning_Data")``` to install a new Swirl course on some of the topics we covered today. The first three modules in that course are pretty useful for class (although you may like the Datacamp videos and exercises better - they cover a lot of the same ground).

**Comment by lkwhite** [comment]
This blog post has been making the rounds on Twitter this week and may resonate for several of you - [R for Excel users by Gordon Shotwell](http://blog.yhat.com/posts/R-for-excel-users.html):

> **Obstacle # 2:** The mental model underlying the tool is different from your current mental model
>
>The way the new tool wants you to think about the problem is different from the way you are used to thinking about the problem. For instance, if you are used to putting your analysis in a rectangular grid, then moving to a tool which is designed around procedural commands is going to be difficult.
>
>In my opinion obstacle # 2 is by far the larger barrier for Excel users. Most of the people who learn R have some basis in programming. The mental models underlying languages like Matlab or Python, as well as statistical packages like SPSS and SAS, have a lot in common with R, and there are many resources available for translating the bits which don't make sense. Excel makes you think about analytical problems in a very different way, and there aren't very many resources for translating the two paradigms.

Gordon runs through a nice compare & contrast of the workflows for joining two tables together and performing a few calculations that data. It's a good example of powerful the tidyverse is when it comes to iterating through variations on that same process in R, but he's also not dismissive of the mental gearshifting required if you've been analyzing your data in Excel forever.  Also there are bonus _Kill Bill_ gifs about the universal struggles of learning a programming language, because hey, it's the internet.

**Comment by kriemo** [comment]
Here's two other useful R-esources that may be helpful:
  1) The chapter on tidy-data found in the [R for data science book](http://r4ds.had.co.nz/tidy-data.html).

  2) The [MOLB7621/tidyrdatasets](https://github.com/MOLB7621/tidyrdatasets) repository contains examples of dplyr/tidyr approaches to tidying the built-in R datasets.

**Comment by etiennedanis** [comment]
Thank you very much for all the R-esources!
I have a question related to the problem-set-3.
Could you explain the problem/question 4 with some examples?
I have a bit of trouble to understand what this question is about.
Thank you so much in advance!
Etienne
