### ISSUE TITLE
Room update for March 28

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7950/Discussion#44]
Our normal location is unavailable on March 28. We'll hold class in RC1 North Room 1309. I think this  room will hold everyone (fingers crossed). Tell your friends.

cc @MOLB7621/students

**Comment by lkwhite** [comment]
Reminder that class today is in RC1N 1309 instead of our usual location in Ed2.

@MOLB7621/students @MOLB7621/tas @MOLB7621/instructor

**Comment by kriemo** [comment]
Reminder that today class is back in our normal room in Ed2 

@MOLB7621/students
