### ISSUE TITLE
Final project idea for people without their own data

### ISSUE THREAD

**Issue by lkwhite** [MOLB7950/Discussion#46]
This is a _proposed_ final project for anyone who doesn't have their own data they'd prefer to analyze. Inspired by my experience piloting [Geo2Enrichr](http://amp.pharm.mssm.edu/g2e/about) in [Avi Ma'ayan](http://labs.icahn.mssm.edu/maayanlab/)'s 2015 Coursera course, plus some other discussions with Kent and a few students in the class. 

If you're considering doing this, I've provided a fair bit of documentation below to get you started, but feel free to take this in a slightly different direction if a piece of what I've written below interests you. You may want to reply to this thread to coordinate with others on how to tackle this project - I know @etiennedanis asked me to post more about this idea today, and we had ~7 folks without their own data who can either take on this project or working more with [NIH exporter](http://jayhesselberth.github.io/nihexporter/) to analyze funding data.

### Background
When you perform a sequencing experiment and get back your results, the first thing you usually do is align that data to a genome. If you work on the budding yeast _Saccharomyces cerevisiae_, you'd align your reads to the most recent yeast genome build SacCer3, and then take those aligned reads forward in the rest of your analysis. But what about the sequencing reads that _don't_ align to your genome of interest, or that otherwise don't fit the parameters of your analysis? Bioinformatics pipelines routinely discard reads, especially reads that could come from technical artifacts in sequencing library preparation. However, these trashed reads can also sometimes contain interesting data, like evidence of noncanonical RNA splicing or even reads from other organisms. Sometimes re-analyzing these reads can even be worthy of publication on its own. For instance:
* In [Mapping the RNA-seq Trash Bin](https://www.ncbi.nlm.nih.gov/pubmed/23702463), researchers re-analyzed published transcriptome sequencing from prokaryotes, and speculate on how these "trash heap" reads could represent noncanonical RNA splicing events or RNA processing steps.
* This [RNA-seq dumpster diving](http://biorxiv.org/content/early/2016/05/13/053041) preprint got some buzz last summer. While working on samples from asthmatic patients, the authors tried to build a better computational protocol to account for genomic diversity in immune cells as well as other sources of read diversity, like microbial reads.
* In [this analysis](https://www.ncbi.nlm.nih.gov/pubmed/26714747) of unmapped reads from the _Bos taurus_ genome project, the authors identified a diverse array of invertebrate parasites that appear to be infecting the reference cow. (Ew.)
* In [this re-analysis of ribosome profiling data](https://www.ncbi.nlm.nih.gov/pubmed/26900662), some Boston-based researchers examined reads that were the wrong size to be ribosome-protected footprints. These normally-discarded reads showed conserved sequences of discrete sizes consistent with protection from RNase cleavage by other RNA-binding proteins.  
* Unmapped reads can also [come from contaminants](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4552482/), which can sneak in at any stage from sample collection to sequencing.

### What can we learn from the reads others discard?
This group project is aimed at getting you acquainted with publicly-available genomic data sources, practicing your command line skills, and encouraging you to get creative exploring real data in R. By collaborating in class and on GitHub, you'll work together to find some interesting sequencing data from human samples, where the data files are split into two groups - cases and controls. You can then look at the reads from these datasets that _don't_ map to the human genome and explore differences between case and control datasets, which should allow you to ask a number of interesting biological questions, such as:
* How prevalent is contamination in public sequencing datasets?
* What organisms can we identify in the sequencing "junk pile"?
* Are there data sets where the unmapped reads significantly differ between cases and controls, suggesting a possible association between a non-infectious disease and an infectious organism?

### General suggestions - start small, stick to viruses, choose your data wisely
* Viruses have small genomes, which makes aligning to them less computationally intensive. If we stick to exploring viral reads in human data, your analyses shouldn't take forever to run.
 * As a group, we should decide on one standard viral reference to align to. [This blog post](http://www.cureffi.org/2013/01/25/aligning-unmapped-reads-to-viral-genomes/) outlines a potential strategy for doing so.
* You can work alone or in small groups. If you work in a group, we'll expect you to analyze more data than if you were working solo. Either way, you are *highly* encouraged to collaborate with your fellow students to a) select different different data sets, and b) come up with the best ways to analyze everyone's data.
* If you're working alone, choose a small number of public data files from a _single_ study in the NCBI [Gene Expression Omnibus (GEO)](https://www.ncbi.nlm.nih.gov/geo/). Six files representing a single biological comparison with three replicates or samples for each condition is a good number to shoot for. 
* It's worth getting acquainted with the types of files in GEO and how to search, filter, and download GEO datasets before you start downloading data. Remember that you want a dataset with:
  * pairs of human data (disease vs. control - but not an infectious disease!)
  * from a high throughput sequencing experiment (DNA or RNA)
  * without drug treatment or other experiment variables that could confound your analysis
  * ideally with a few replicates

### Starting analysis workflow
* Pick a study from GEO and tell the class about it on GitHub
* Align the sequencing data to the human reference (hg38) and save the unmapped reads to a new file
  * This step will probably be the most computationally intensive
  * If it becomes a bottleneck, ask a TA for help running this job on the cluster for you
* Align the unmapped reads to our class reference file of human virus genomes
* Look at your data and explore

### Questions you might want to examine:
* What % of reads map to the human genome? What % map to viruses that infect humans?
* Which (if any) viruses are in your samples?
* How abundant are they? (Hint:  *(no. of reads * read length) / (length of virus genome)* is a decent proxy for viral copy number in a sample.)
* How much coverage do you see across a particular virus genome? Are there regions that lack coverage?
* Which viral genes are expressed? Do they share anything in common?
* Is there an equal number of viral reads in both cases and controls? If so, do you think this is due to contamination?
* Is there a difference in viral reads between cases and controls? If so, do you think this is a genuine disease association?
* What happens when you examine more replicates from the same study?
* Other ideas you come up with as you explore your data. Be creative!

### Communicating your findings and documenting your workflow
All of your work can be saved in an Rmarkdown file, starting with downloading your data sets from GEO all the way to that awesome ggplot2 visualization you want to share with your classmates. Remember, Rmarkdown files can accept code chunks that use languages _other_ than R if you specify that at the beginning of the block, such as: 

\```{bash, eval = FALSE}
cat file1.csv file2.csv > file3.csv
\```

The ```eval = FALSE``` statement in the block above tells R not to execute that chunk of code when you run the entire markdown file - a handy trick if you don't want to re-download the same starting files every time you re-run your analysis.

I suggest using an Rmarkdown file to show off both your exploratory analysis and your results (whether positive or negative!), with a combination of written descriptions, code blocks, and visuals. If you feel like trying out something new in R (performing more complex statistical tests, drawing a phylogenetic tree, or making an interactive app with [Shiny](https://shiny.rstudio.com/)) now's the time. For your final presentation, include 2-3 interesting and well-labeled plots with written descriptions of how you explored your data and what you found.

**Comment by kriemo** [comment]
A recent study from Craig Venter's group performed an analysis from DNA-Seq data to try to define the blood `virome`. They analyzed 1 petabyte (!) of data.

[The blood DNA virome in 8,000 humans](http://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1006292)
