### ISSUE TITLE
Remaining classes

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7950/Discussion#47]
- Class 15 (T Mar 28) - ???
- Class 16 (Th Mar 30) - ???
- Class 17 (T Apr 4) - ???
- Class 18 (Th Apr 6) - [Filing bug reports / reproducible examples](https://twitter.com/brent_p/status/842751872792322048)
- Class 19 (T Apr 11) - Snakmake
- Class 20 (Th Apr 13) - mRNA-seq redux
- Class 21 (T Apr 18) - ChIP-seq redux
- Class 22 (T Apr 25) - Variant calling
- Class 23 (Th Apr 27) - Final project presentations

**Comment by kriemo** [comment]
* Class 15 (T Mar 28) - Python Intro
* Class 16 (Th Mar 30) - Python basic use cases
* Class 17 (T Apr 4) - Python more advanced examples
