### ISSUE TITLE
Python basics cheatsheet

### ISSUE THREAD

**Issue by lkwhite** [MOLB7950/Discussion#48]
The folks at DataCamp just released a Python for beginners [cheatsheet](https://www.datacamp.com/community/tutorials/python-data-science-cheat-sheet-basics#gs.pRU48dc). It covers many of the same concepts Jay went over in [class 15](http://molb7621.github.io/workshop/Classes/class-15.html) today on a single page. @MOLB7621/students

**Comment by shawjes** [comment]
Hi Laura,


Could you please re-send the invitation to the DataCamp group?


Thank you!


Jessica Shaw
Genetic Biostatistician,Colorado Center for Personalized Medicine
815-975-7515<tel:815-975-7515> | www.linkedin.com/in/jessicarshawco<http://www.linkedin.com/in/jessicarshawco>

________________________________

**Comment by lkwhite** [comment]
Done (sent to your ucdenver account).

**Comment by shawjes** [comment]
Sorry, I didn't get an email... I wonder if it's getting blocked from my inbox or something. Did you send it to jessica.shaw@ucdenver.edu?


Jessica Shaw
Data Manager and Statistical Analyst, LEAD Center
M.S. Biostatistics student, CU Denver
815-975-7515<tel:815-975-7515> | www.linkedin.com/in/jessicarshawco<http://www.linkedin.com/in/jessicarshawco>

________________________________

**Comment by jayhesselberth** [comment]
Jessica – yes I sent it to your ucdenver account. Can you check your spam/clutter boxes?

**Comment by shawjes** [comment]
I'm searching all folders, including my junk and clutter folders, for "Datacamp" and nothing is coming up. No idea why... Can you try to send it to my gmail instead? jessica.rose.shaw@gmail.com.


Jessica Shaw
Data Manager and Statistical Analyst, LEAD Center
M.S. Biostatistics student, CU Denver
815-975-7515<tel:815-975-7515> | www.linkedin.com/in/jessicarshawco<http://www.linkedin.com/in/jessicarshawco>

________________________________
