### ISSUE TITLE
RNA-Seq / ChIP-Seq review class

### ISSUE THREAD

**Issue by kriemo** [MOLB7950/Discussion#54]
I've had a few requests from people for a review of ChIP-Seq and RNA-Seq workflows, with an emphasis on the code necessary to process the raw sequencing data (fastq) all the way to meaningful results.  I'd be willing to teach an optional class or hold an informal meeting depending on the interest level. 

**Please respond here if you think you would attend such a class.** Thanks. 

@MOLB7621/students @MOLB7621/tas @MOLB7621/instructor

**Comment by tshaikh10** [comment]
Yes. I would definitely want to attend this class.

**Comment by hudishl** [comment]
Yes I will be there

**Comment by shawjes** [comment]
I would be interested.


Thanks!


Jessica Shaw
Genetic Biostatistician, Colorado Center for Personalized Medicine
815-975-7515<tel:815-975-7515> | www.linkedin.com/in/jessicarshawco<http://www.linkedin.com/in/jessicarshawco> | View My Availability<https://outlook.office365.com/owa/calendar/607a059745fa4e16bdc5f6bbd809a4a0@UCDENVER.EDU/6b88e05c739d4ceba8daa2d8a621c6f06317324414448577771/calendar.html>

________________________________

**Comment by etiennedanis** [comment]
I am interested and will be there too!

Etienne

**Comment by kiekhaec** [comment]
Yes. This would be great.

Thanks

Carol

Sent from my iPhone

On Apr 13, 2017, at 2:42 PM, tshaikh10 <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes. I would definitely want to attend this class.

**Comment by stefanhaugen** [comment]
yes please. thanks in advance!

**Comment by anndoan** [comment]
I would attend this class. Thanks.

**Comment by dslorber** [comment]
I would also attend!

**Comment by shawnspei** [comment]
Very much interested!!! Sounds great!

**Comment by kriemo** [comment]
Ok. Thanks for the responses. There are enough people interested that I will teach this class in our normal room in ED2 North on April 25th from 1-3 pm.

**Comment by eprince1991** [comment]
I would be interested in such a class.

Eric Prince
